# NUMPY ARRAY

In [3]:
import numpy as np

In [2]:
np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [77]:
my_list=[1,2,3]

# array

In [76]:
np.array(my_list)

array([1, 2, 3])

In [53]:
a1=np.array(my_list)

In [54]:
a1

array([[ 1,  2,  3],
       [23,  3,  2],
       [ 1,  2,  3]])

In [55]:
my_list=[[1,2,3],[23,3,2],[1,2,3]]

In [78]:
np.array(my_list)

array([1, 2, 3])

# arange zeroes onces and eye 

In [79]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [81]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.zeros((7,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
np.linspace(1,25,50)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [68]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
np.eye((7))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### Rndom

In [72]:
np.random.rand(10)

array([0.64466606, 0.30813443, 0.53297146, 0.47050144, 0.20582286,
       0.49431292, 0.13513247, 0.56229413, 0.38284699, 0.75743564])

In [98]:
np.random.rand(5,4) # rand return uniform distribution [0,1)

array([[0.23048473, 0.05875294, 0.82049501, 0.41808525],
       [0.8427301 , 0.64113756, 0.48500959, 0.62045538],
       [0.41834373, 0.3466844 , 0.16181043, 0.99153957],
       [0.59927025, 0.08365069, 0.192526  , 0.73354912],
       [0.32462077, 0.47225415, 0.9349994 , 0.2645146 ]])

In [97]:
np.random.randn(10)  # randn  return sample from normal distribution

array([ 0.28749214, -0.01840346, -0.65148163,  1.26996744,  0.22781835,
        0.07396061, -0.35886477, -1.30289461, -0.82003575, -0.19183246])

In [95]:
np.random.randn(5,5)

array([[-0.4914209 ,  0.96031754,  2.01840077,  0.67746254, -0.06080103],
       [-0.87238121, -0.8531298 ,  1.07942932, -0.01396756, -0.72486517],
       [-0.03027059, -0.11423261, -0.08086481, -0.107157  , -0.72670486],
       [ 1.1172793 ,  1.18923551, -2.31690895,  0.32479162,  0.35696388],
       [-2.3289579 ,  1.88845386, -0.85935286,  1.00498063, -0.06356757]])


### randint

In [101]:
np.random.randint(0,100,10)

array([32, 60, 56, 33, 57, 34, 89, 56, 84, 92])

In [102]:
np.random.randint(4,20)

10

## Array attribute and Methods

In [4]:
ar=np.arange(25)
randar=np.random.randint(0,25,10)

In [5]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
randar

array([23,  1,  4, 16, 24,  4,  1, 21, 19, 12])

### Reshape 

In [20]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# max min argmax argmin

max min value using max ,min  or there location using argmax ,argmin

In [8]:
ar.max()

24

In [9]:
ar.min()

0

In [10]:
ar.argmax()

24

In [11]:
randar.argmax()

4

In [12]:
randar.max()

24

In [18]:
ar.dtype

dtype('int32')

In [19]:
ar.shape

(25,)

In [22]:
ar.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int32)

In [23]:
ar.base

In [24]:
ar.any

<function ndarray.any>