# index and selection

In [26]:
import numpy as np

In [27]:
arr=np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [30]:
arr[5:]

array([5, 6, 7, 8, 9])

In [31]:
slice_arr=arr[5:7]

In [32]:
slice_arr

array([5, 6])

In [37]:
slice_arr[:]=100 # importanat orignal array also change

In [36]:
slice_arr

array([100, 100])

In [38]:
arr # orignal also change

array([  0,   1,   2,   3,   4, 100, 100,   7,   8,   9])

In [39]:
# reset array
arr=np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# arry copy

arry_copy=arr[1:7].copy()

In [56]:
arry_copy

array([1, 2, 3, 4, 5, 6])

In [57]:
arry_copy[:]=10

In [58]:
arr # no change in orignal copy ! This avoid memory proble

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arry_copy

array([10, 10, 10, 10, 10, 10])

# indexing 2d array (Matrix)

In [61]:
arr=np.array([1,2])

In [62]:
arr

array([1, 2])

In [66]:
arr_2d=np.array([[1,2,3],[44,3,2],[3,5,2]])

In [67]:
arr_2d

array([[ 1,  2,  3],
       [44,  3,  2],
       [ 3,  5,  2]])

In [70]:
arr_2d[0][2]

3

In [98]:
arr_2d[0,2] # good for ExtrActing subarry

3

In [120]:
arr_2d[0:3][1:3]  # can't get subarry  PROPERLY

array([[44,  3,  2],
       [ 3,  5,  2]])

In [114]:
arr_2d[1:2,1:2] 

array([[3]])

In [118]:
arr_2d[0:3,1:3]     # ( ] FIRST INCLUDE LAST EXCLUDE 

array([[2, 3],
       [3, 2],
       [5, 2]])

# FANCY ARRAY

In [188]:
arr2d=np.zeros((10,10))


In [189]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [190]:
arr2d_lenght=arr2d.shape[1]

In [191]:
arr2d_lenght

10

In [196]:
for i in range(arr2d_lenght):
    arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [160]:

# Allow in any order
arr2d[[2,3,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [163]:
arr2d[[6,3,5]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

# selection

In [164]:
arr=np.arange(0,11)

In [165]:
arr>7

array([False, False, False, False, False, False, False, False,  True,
        True,  True])

In [171]:
arr_bool=arr>5

In [172]:
arr[arr_bool]

array([ 6,  7,  8,  9, 10])

In [173]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [181]:
arr[arr<8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
~