# NUMPY OPERATION

In [1]:
import numpy as np

In [2]:
arry=np.arange(10)

In [3]:
arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arry +arry

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arry*arry

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arry**arry

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [8]:
1/arry

C:\Users\negi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
np.log(arry)

C:\Users\negi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [10]:
np.exp(arry)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
arry/arry

C:\Users\negi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])