In [1]:
import sklearn.datasets as datasets

In [2]:
df = datasets.load_iris()

In [3]:
df.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
X= df['data']
X.shape

(150, 4)

In [5]:
y=df['target']
y.shape

(150,)

In [6]:
from sklearn.model_selection import train_test_split

In [168]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [169]:
import tensorflow.contrib.learn.python.learn as learn
import   tensorflow as tf

In [180]:
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

classifier=learn.DNNClassifier(hidden_units=[10,10,10,10,10,10,10,10],n_classes=3,feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001A28A3A8470>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_eval_distribute': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_protocol': None, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'C:\\Users\\negi\\AppData\\Local\\Temp\\tmp7hure4kn'}


In [181]:
feature_columns.index

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [182]:
classifier.fit(X_train,y_train,steps=200,batch_size=32)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\negi\AppData\Local\Temp\tmp7hure4kn\model.ckpt.
INFO:tensorflow:loss = 1.0912664, step = 0
INFO:tensorflow:global_step/sec: 350.587
INFO:tensorflow:loss = 0.4809761, step = 100 (0.287 sec)
INFO:tensorflow:Saving checkpoints for 200 into C:\Users\negi\AppData\Local\Temp\tmp7hure4kn\model.ckpt.
INFO:tensorflow:Loss for final step: 0.35544658.


DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x000001A28A7CAC88>, 'hidden_units': [10, 10, 10, 10, 10, 10, 10, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x000001A1D91FB6A8>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [183]:
prediction  = list(classifier.predict(X_test))

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\negi\AppData\Local\Temp\tmp7hure4kn\model.ckpt-200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [184]:
from sklearn.metrics import classification_report,confusion_matrix

In [185]:
#prediction  # make list


In [186]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.86      1.00      0.93        19
           2       1.00      0.84      0.91        19

   micro avg       0.94      0.94      0.94        50
   macro avg       0.95      0.95      0.95        50
weighted avg       0.95      0.94      0.94        50



In [187]:
print(confusion_matrix(y_test,prediction))

[[12  0  0]
 [ 0 19  0]
 [ 0  3 16]]


# train data 

In [188]:
prediction  = list(classifier.predict(X_train))

INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\negi\AppData\Local\Temp\tmp7hure4kn\model.ckpt-200
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [189]:
print(classification_report(y_train,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.86      0.97      0.91        31
           2       0.96      0.84      0.90        31

   micro avg       0.94      0.94      0.94       100
   macro avg       0.94      0.94      0.94       100
weighted avg       0.94      0.94      0.94       100

